const placeBook = [
    {   
        id: 1,
        image: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_hanoi_1.jpg',
        place: "Ha Noi",
        description: "Land of a thousand years of civilization.",
        star: 5,
        star_img: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_star.png',
        moon: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_moon.png',
        mountain: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_mountion.png',
        valley: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_valley.png',
        singer: 'https://hoangphuc0304.github.io/VMusic/assets/image/singer_den.jpeg',
        background: 'background-night',
        color: 'color-night',
    },
    {   
        id: 2,
        image: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_danang_2.jpg',
        place: "Da Nang",
        description: "The place always attracts millions of visitors every year, the tourist center of central Vietnam.",
        star: 4,
        star_img: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_star.png',
        moon: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_moon.png',
        mountain: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_mountion.png',
        valley: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_valley.png',
        singer: 'https://hoangphuc0304.github.io/VMusic/assets/image/singer_amee.jpg',
        background: 'background-sunset',
        color: 'color-sunset',
    },
    {   
        id: 3,
        image: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_saigon_1.jpg',
        place: "Sai Gon",
        description: "Pearl of the Orient - the holy land of those who cherish to change their lives.",
        star: 5,
        star_img: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_star.png',
        moon: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_moon.png',
        mountain: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_mountion.png',
        valley: 'https://hoangphuc0304.github.io/VMusic/assets/image/book_valley.png',
        singer: 'https://hoangphuc0304.github.io/VMusic/assets/image/kind_sontungmtp_2.png',
        background: 'background-dawn',
        color: 'color-dawn',
    },
]

export default placeBook